# Generated by Django 5.2 on 2025-04-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('education', '0005_user_teacher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercourseclass',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.class'),
        ),
        migrations.AlterField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(related_name='courses', through='course.TeacherCourseClass', to='education.class'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
