# Generated by Django 4.1.8 on 2025-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_teachercourseclass_class_obj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
