# Generated by Django 4.1.8 on 2025-04-11 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('deploy_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teachercourseclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teachercourseclass',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercourseclass',
            name='end_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercourseclass',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachercourseclass',
            name='start_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='teachercourseclass',
            constraint=models.UniqueConstraint(fields=('course', 'class_obj'), name='unique_course_class'),
        ),
        migrations.AddField(
            model_name='homework',
            name='course_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.teachercourseclass'),
        ),
        migrations.AddField(
            model_name='homework',
            name='deployer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
