# Generated by Django 4.2 on 2025-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_assignmentsubmission_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
