# Generated by Django 4.2 on 2025-06-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_assignmentsubmission_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='submitted',
            field=models.BooleanField(default=True),
        ),
    ]
