# backend/course/migrations/0010_rename_homework_assignment_and_more.py
# Generated by Django 4.2 on 2025-06-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0009_alter_assignmentsubmission_submitted'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='Assignment', # Homework 模型被重命名为 Assignment
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='submissions', # related_name 已经正确更新
                to='course.Assignment' # <--- 这是问题所在，应该指向新的模型名 'course.Assignment'
            ),
        ),
    ]