# Generated by Django 4.2 on 2025-06-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_homework_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ai_grading_enabled',
            field=models.BooleanField(default=False, verbose_name='启用AI辅助批改'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='ai_grading_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='AI辅助批改提示词'),
        ),
    ]
