# Generated by Django 4.2 on 2025-06-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_assignment_ai_grading_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_comment',
            field=models.TextField(blank=True, null=True, verbose_name='AI评语'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_generated_similarity',
            field=models.FloatField(blank=True, null=True, verbose_name='AI生成疑似度'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_grading_status',
            field=models.CharField(blank=True, choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], default='pending', max_length=20, null=True, verbose_name='AI批改状态'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_grading_task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='AI批改任务ID'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AI评分'),
        ),
    ]
