# Generated by Django 4.2 on 2025-06-08 02:09

import chatroom.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0012_assignmentsubmission_ai_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='聊天室名称')),
                ('is_muted', models.BooleanField(default=False, verbose_name='全员禁言')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tcc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='course.teachercourseclass', verbose_name='关联教学班')),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default=chatroom.models.generate_random_nickname, max_length=50, verbose_name='群内昵称')),
                ('role', models.CharField(choices=[('member', '普通成员'), ('admin', '管理员')], default='member', max_length=10, verbose_name='角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在群内')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chatroom.chatroom', verbose_name='聊天室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'ordering': ['joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('video', '视频'), ('file', '文件'), ('system', '系统消息')], default='text', max_length=10)),
                ('content', models.TextField(verbose_name='消息内容')),
                ('file_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Minio文件路径')),
                ('file_original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='原始文件名')),
                ('thumbnail_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='缩略图路径')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chatroom.chatroommember', verbose_name='作者')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatroom.chatroom', verbose_name='聊天室')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
