# Generated by Django 5.1.7 on 2025-04-04 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='class_group',
            new_name='class_enrolled',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='material',
            name='visible_classes',
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='学分'),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='课时'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='任课教师'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='真实姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='announcementread',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.CreateModel(
            name='TeacherCourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook', models.CharField(blank=True, max_length=200, null=True, verbose_name='使用教材')),
                ('syllabus', models.TextField(blank=True, null=True, verbose_name='教学大纲')),
                ('progress', models.TextField(blank=True, null=True, verbose_name='教学进度')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_arrangements', to='education.class', verbose_name='班级')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_arrangements', to='education.course', verbose_name='课程')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='教师')),
            ],
            options={
                'verbose_name': '教师课程班级关联',
                'verbose_name_plural': '教师课程班级关联',
                'unique_together': {('teacher', 'course', 'class_group')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='teaching_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.teachercourseclass', verbose_name='所属教学班'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='teaching_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='education.teachercourseclass', verbose_name='所属教学班'),
        ),
    ]
