# Generated by Django 5.2 on 2025-04-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_homework_alter_teachercourseclass_unique_together_and_more'),
        ('education', '0005_user_teacher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('lecture', '课件'), ('example', '教学示例'), ('software', '软件安装包'), ('reference', '参考资料'), ('other', '其他')], default='other', max_length=20, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='material',
            name='teaching_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.teachercourseclass', verbose_name='所属教学班'),
        ),
    ]
