# Generated by Django 4.2 on 2025-05-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_material_material_type_alter_material_teaching_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='院系'),
        ),
        migrations.AddField(
            model_name='class',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业'),
        ),
    ]
