# Generated by Django 4.2 on 2025-06-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_class_department_class_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='头像路径 (MinIO)'),
        ),
    ]
