# Generated by Django 4.2 on 2025-06-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论内容 (Markdown/HTML)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='内容 (Markdown/HTML)'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file_path',
            field=models.CharField(max_length=512, verbose_name='Minio文件路径'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file_type',
            field=models.CharField(choices=[('IMAGE', '图片'), ('VIDEO', '视频'), ('FILE', '文件'), ('GIF', '动图')], max_length=10, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='缩略图路径'),
        ),
    ]
